### ISSUE TITLE
Beef up README

### ISSUE THREAD

**Issue by ciberch** [seevibes/twitter_ads#2]
Can you do CRUD on Ads ? What are all the possible operations

**Comment by tomsoft1** [comment]
Not sure in which sense you are asking the question but yes we do CRUD on ads. The supported operation for now are the followings:

main :

     get: [:bidding_rules, :iab_categories]

Account:

        :get => [
          :promoted_accounts, :promoted_tweets, :tailored_audience_changes,
          :targeting_criteria, :app_lists, :campaigns, :funding_instruments,
          :line_items, :promoted_accounts, :promotable_users, :reach_estimate,
          :targeting_suggestions,:tailored_audiences
        ],
        :post => [:tailored_audiences, :tailored_audience_changes, :campaigns],
        :put => [:campaigns, :promoted_tweets, :targeting_criteria],
        :delete => [:tailored_audiences, :campaigns, :promoted_tweets, :targeting_criteria]

**Comment by ciberch** [comment]
Ok thanks @tomsoft1
